### ISSUE TITLE
Support Oledb connection for Teradata (or some other databases) connection-strings

### ISSUE THREAD

**Issue by Seddryck** [Seddryck/NBi#101]
Currently, when you define an oldeb connection for a Teradata source, NBi is not able to find it's an Oldeb connection string and just throw an exception.

NBi should support Teradata, MySql and some other well-know connection-strings for oledb.

**Comment by MarcoCh** [comment]
Thank you for taking in consideration this feature in v1.11

About this issue currently I'm tring to make an oledb connection not only to Teradata but also to Oracle (this one using the Oracle OleDb provider, as recomended).
First of all, I want to ask you in which architecture did you build the project, currently I'm building it on x64 and send me some warnings about compatibility with the references to the new providers (Teradata and Oracle).
In the issue #99 you mentioned that in order to allow a new provider to a connection, there are some changes to be done in connectionFactory.cs and probably create a queryteradataengine.cs, but if is not much trouble, could you explain it a little bit more what changes do I have to do, what references, other than the providers do I have to add.
About the references, for Oracle I'm using Oracle.DataAccess (Oracle OleDb provider) in stead of System.Data.Oracle

Sorry for the troubles and thank you for consider the request to connection to Teradata, MySQL, Oracle, etc

**Comment by Seddryck** [comment]
The configuration for the build is the "Active".

![configuration-nbi](https://cloud.githubusercontent.com/assets/5455045/9026072/2fdedb52-3921-11e5-9227-0cf82939ea2e.png)

If it's an OleDb provider, you shouldn't add any reference to the project. The idea is just to use the OleDbConnection (already referenced). That's why this change should be easy: you just need adapt the method InterpretProviderName in ConnectionFactory to be sure that this class instantiate an OleDb Connection. Now it's possible that you've some troubles with the method TranslateProviderName but you should be able to fix this with GetSpecific.

If you need/want to reference an additional dll then in you're in the case of issue #102 and it's much more complex. I won't work on this one until I've received some feedback from #97 and have more experience with provider with a deep look in #101.

**Comment by Seddryck** [comment]
I've added a way to define the association between the information 'provider' in the connectionString and the associated provider.

To achieve this you need to add the `providers` element in your config file. In the example, here under, we're associating "Microsoft.ACE.OLEDB.12.0" (Excel, Access, ...) to "System.Data.OleDb". It means that the connection-string defined here under will create a System.Data.OleDb.Connection ... then NBi will continue to work as usual.

config file:

``` xml
<nbi testSuite="...">
    <providers>
      <add id="Microsoft.ACE.OLEDB.12.0" invariant-name="System.Data.OleDb"/>
    </providers>
</nbi>
```

connection string:

``` xml
<query connectionString="Provider=Microsoft.ACE.OLEDB.12.0;Data Source=Acceptance\Resources\Positive\OrderCountByYear.xlsx;Extended Properties=&quot;Excel 12.0 Xml;HDR=YES&quot;">
```

So, at the moment NBi only supports System.Data.OleDb, System.Data.SqlClient, System.Data.Odbc and Microsoft.AnalysisServices.Adomd connections. Other kind of connections will not work (Perhaps in 1.12 but not sure)!

When using Teradata, Oracle, MySQL or any other database, you must ensure that your provider is effectively supporting one of these connection and be sure to add the provider information in your config file.

The preview is available at https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.11.0.99052
