### ISSUE TITLE
Connection string and report dataset

### ISSUE THREAD

**Issue by amitsinghmiet** [Seddryck/NBi#122]
We are creating a test case to extract a query from dataset of a report and run a test against it. While doing so NUnit is throwing an error stating Connection String is missing. Though in the documentation it is mentioned that connection string is optional. In case we provide a connection string, wouldn't the test case will become a database related test case instead of report based one. How can we proceed in such cases?

**Comment by Seddryck** [comment]
Could you provide a link to the page stating that the connection string is optional?

Could you describe the test that you're trying to implement?

**Comment by amitsinghmiet** [comment]
Link to the page stating "Connection string is option" http://www.nbi.io/docs/query-report/
For more clarification, here is the screen grab of the page
![nbi report connection string](https://cloud.githubusercontent.com/assets/14869676/10218878/3940909e-67ef-11e5-829a-90818af9575f.JPG)

We are trying to query the dataset of a report; on providing a random connection string (which seems mandatory for the test case to load without any error), test case is stating an error that a column of the dataset has wrong syntax. We can't do any tweaking with column as it might interfere with the report that is deployed.

**Comment by Seddryck** [comment]
Hi,

You should read the end of the sentence: if you don't provide a connection string you should use the features `default` or `references`. 

If my understanding is correct, what you're trying to achieve is a nonsense. You should talk with one of your colleague with a minimal knowledge of SSRS or read a few articles about it to understand how it works. 

I don't want to be rude but I can't help you because your questions are not related to this tool. You should ask basic questions to stackoverflow or any similar website.
