### ISSUE TITLE
SSIS Package with problems in derived column

### ISSUE THREAD

**Issue by RitaBI** [Seddryck/NBi#178]
Hi,

I'm trying to run a package but it was returned a problem related with derived column.

![image](https://cloud.githubusercontent.com/assets/18401012/14432350/a4f7b6aa-0001-11e6-8ee7-ca03d9862a69.png)

Could you please help me?

Thanks,
Rita Teixeira

**Comment by Seddryck** [comment]
Are you sure you're running your tests on the server? Are you sure your package is effectively running-well without NBi? Have you configured correctly the attribute `version` for your test?

Your problem is not really with NBi but more with your ETL or the configuration of your test

**Comment by RitaBI** [comment]
The package is very simple, it has a source then a derived column and finally the destination. If I remove that derived column it works perfectly but when I use the derived column an error was returned.

The derived column : 
![image](https://cloud.githubusercontent.com/assets/18401012/14435503/17af0db6-0010-11e6-936d-68d7cbd536c0.png)

**Comment by Seddryck** [comment]
The problem is in your package, probably in yoru derivated column component.

If you still think your problem is directly related to NBI, create a reproducible case and then I'll check in detail but at this moment, I've no way to go further in this case.

**Comment by Seddryck** [comment]
Is it too much to get some feedback? You're asking a question, we take time to answer and then ... nothing. This is really a pain in the OSS world, people have no problem to use software for free, to request help for free but they won't take time on their payed hours to close or comment the issue they created.

If your problem is fixed the minimum is to close the question. It'd be nice to comment to share your knowledge/experience with others.

**Comment by RitaBI** [comment]
Sorry for the later answer. The problem was solved and in fact was related with my derived column.

Thank you for your help

**Comment by Seddryck** [comment]
Oki, thx for your feedback.
