### ISSUE TITLE
Schema existence test fails when schema_owner is not 'dbo'

### ISSUE THREAD

**Issue by janvanhumbeek** [Seddryck/NBi#197]
If schema_owner differs from 'dbo', schema existence tests fail.

Fix implemented in pull request: https://github.com/Seddryck/NBi/pull/198

**Comment by Seddryck** [comment]
The fix is correct but it could be a breaking change for some users. So before merging, I'd like to add an optional filter to specify the owner in the xml definition of the objects `schemas` and `schema`. This will ensure that people previously relying on this "invisible" filter will still be able to run their tests successfully with just a minor update.

**Comment by Seddryck** [comment]
Preview available at https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.13.0-ci.77
