### ISSUE TITLE
Bandwidth issue in nbi automation tool

### ISSUE THREAD

**Issue by ankyadu** [Seddryck/NBi#242]
Hi there,

This is Ankit and we have been using NBi tool for automation in our project. One of my colleague has already reached you once to fix Server connection issue.
We have been having issues with the execution and below is the problem description.

Execution becomes un-responsive:

Table has more than 5 million records with 54 columns. We have incorporated the necessary NBi scripts in one file as we want to regression this table in one go.
However if we select more than 10 columns , the tool becomes unresponsive and our network bandwidth reaches its peak. Is this because , the tool loads all the columns data at once to execute or could it be something else which is causing the problem.

Also , i want to know if this tool can be invoked using a SQL Job(execute the given nBits script) which can be scheduled on a timely manner.

Any help on this is much appreciated.

Thanks
Ankit

**Comment by Seddryck** [comment]
1. Not sure than I understand your question. You've one query returning 5.000.000 rows and 54 columns ... and you're suprised to have a bandwith peak? I probably don't get it, can you be more explicit about you're doing by providing the test?

2. You can invoke NBi (in fact nunit-console) with a scheduled task on windows. No need to use SQL Job for this.

**Comment by ankyadu** [comment]
Hi ,

1. Actually I wanted to know is there a way to run my queries efficiently with lesser time of execution. As my queries contains table which contains huge records and usually it takes around 55 minutes to compare two queries.
Any help on this is much appreciated.


Thanks
Ankit Yadav

**Comment by Seddryck** [comment]
Still don't get it. Comparing 1.000.000 rows takes less than 10 seconds in NBi. If you need 55 minutes then it means that your query is slow not the comparison. NBi is a testing tool, not a tool to improve the speed of your query. If your query is slow, then it will be slow within NBi. 

How much time do you need to execute your query in SSMS? 
Have you tried to create multiple queries returning less columns?
Are you sure it's worth it to test the 5.000.000 rows?

**Comment by ankyadu** [comment]
Hi,

I am attaching the screenshot am not able to understand this nbi exception (expected data set has some duplicate keys. I have already checked the keys in SSMS, there are no mismatch in SSMS query. I want to know why there is a mismatch.


![error](https://cloud.githubusercontent.com/assets/25685799/22895341/21a1e724-f242-11e6-8535-0e3f7e991d6c.JPG)

Thanks,
Ankit

**Comment by Seddryck** [comment]
What's the link with previous question(s)? Why do you never answer to my questions and are you expecting answers from me? 

Let me explain a few things about our current conversation (If I can name this a conversation). You're testing (or developing) a BI solution ... that's your job, someone is paying you to do this.  As the creator and the main committer of the OSS product that you're using to achieve this task, I'm developing this during my free time (week-ends, evenings) ... I'm not paid for this and I don't want to be paid for this: it's a hobby. It's always a pleasure to discuss with people about limitations, new features, how-to because they bring something to the project ... after these discussions, I've new ideas, new perspectives, ... their discussion help the project to be better. I'm not expecting something else from them ... they are giving back to the community. 

But when I'm speaking with you (or previously with your colleagues), it's clearly not the case. You're using the tool but never consider the minimum courtesy 

* to read the documentation before asking basic questions, 
* search on the issue tracker if this question has not already been answered 5 times, 
* keep clean the issues tracker by providing feedback (and close the issue) when your case is solved, 
* answering my own questions 

... that's just the counterpart that I'm expecting and apparently it's too much for you. OK, let's switch off this discussion it has no added value for me or for the project and I'm wasting my (free) time ... it's probably better for me to consider to spend this time on new features that the community of users who spent a few hours to read the documentation will be able to use. I decide to make this choice.
