### ISSUE TITLE
How to get test results from NBi?

### ISSUE THREAD

**Issue by gkkarthick2k** [Seddryck/NBi#259]

**Comment by Seddryck** [comment]
What's wrong with you?

Apparently you don't understand the basics of politeness. That's more than enough, I'm blocking you.

**Comment by Seddryck** [comment]
Let me explain a few things about our current conversation (If I can name this a conversation). You're testing (or developing) a BI solution ... that's your job, someone is paying you to do this. As the creator and the main committer of the OSS product that you're using to achieve this task, I'm developing this during my free time (week-ends, evenings) ... I'm not paid for this and I don't want to be paid for this: it's a hobby. It's always a pleasure to discuss with people about limitations, new features, how-to because they bring something to the project ... after these discussions, I've new ideas, new perspectives, ... these discussions help the project to be better. I'm not expecting something else from them ... they are giving back to the community.
But when I'm speaking with you (or previously with your colleagues), it's clearly not the case. You're using the tool but never consider the minimum courtesy to read the documentation before asking basic questions, search on the issue tracker if this question has not already been answered 5 times,
keep clean the issues tracker by providing feedback (and close the issue) when your case is solved,
answering my own questions.

... that's just the counterpart that I'm expecting and apparently it's too much for you. OK, let's switch off this discussion it has no added value for me or for the project and I'm wasting my (free) time ... it's probably better for me to consider to spend this time on new features that the community of users who spent a few hours to read the documentation will be able to use. I decide to make this choice.
