### ISSUE TITLE
<variables> tag generated incorrectly using the genbil

### ISSUE THREAD

**Issue by fefeslon** [Seddryck/NBi#323]
Hey,

Using the latest build and genbil, after generating the tests the <variables> tag is generated incorrectly (see the screenshot).

![image](https://user-images.githubusercontent.com/25638272/33476166-4de42986-d681-11e7-9992-4f6b40ac28b8.png)

It has to be deleted/corrected manually so the test suite can be run.

**Comment by Seddryck** [comment]
Thx for reporting! Tonight, I will add a fix to be sure that  if ```variables``` is empty, it won't be included in the generated test-suite.

But could you clarify if this empty tag was causing some issues at the execution or not? And If yes could you post the stacktrace?

Thx.

**Comment by Seddryck** [comment]
Ok, I understood that the key issue was that the Xml file generated by genbi was not valid according to XSD due to the empty element ```variables```. I fixed the generation of the empty tag.

Beta is available at https://ci.appveyor.com/project/Seddryck/nbi/build/1.17.0-beta.109.build.224 
Thx again for reporting.

**Comment by fefeslon** [comment]
Hey,

Exactly as you wrote above. 
Generated Xml file was not valid so it had to be corrected manually.

Works now, thanks for quick fix.
