### ISSUE TITLE
Q: Nunit 3 or higher support?

### ISSUE THREAD

**Issue by barth11** [Seddryck/NBi#407]
Hi @Seddryck,

According to documentation the nbi does not support Nunit 3 or higher. Is this going to change in the near future?

Thanks.

Jakub

**Comment by Seddryck** [comment]
This topic is discussed in the issue #308 

Could you elaborate in the thread #308 why is it important for you to support NUnit 3.x? I mean which features are lacking in NBi or NUnit 2.x and would be there if we move to NUnit 3.x I need this information because currently the portage to NUnit 3.x is not a top-priority due to missing real use-cases!
