### ISSUE TITLE
Compare 2 recordsets

### ISSUE THREAD

**Issue by win32nipuh** [Seddryck/NBi#437]
Does it make sense to compare 2 recordsets from the same query? 
Can this kind of tests give hash confusing during the tests?
 Something like this:

```xml
<test name="Compare two query results">
  <system-under-test>
    <execution>
      <query>
        select * from FirstTable;
      </query>
    </execution>
  </system-under-test>
  <assert>
    <equalTo>
      <query>
       select * from FirstTable;
      </query>
    </equalTo>
  </assert>
</test>
```

**Comment by win32nipuh** [comment]
I have found the sample: QueryEqualToQuery.nbits. It contains one of example:
Why its name is: "'Reseller Order Count' by year before 2006"?
The queries do not contain any operations to count orders etc.

There are 2 identical queries to compare. What is the sense?

```xml
<test name="'Reseller Order Count' by year before 2006" uid="0001" ignore="false">
    <condition>
      <service-running name="MSOLAP$SQL2017" />
    </condition>
    <system-under-test>
      <execution>
        <query name="MDX Except" connectionString="Provider=MSOLAP.4;Data Source=(local)\SQL2017;Initial Catalog='Adventure Works DW 2012';localeidentifier=1049">
          select
          [Measures].[Internet Order Count] on 0,
          [Date].[Date].Children  on 1
          from
          [Adventure Works]
        </query>
      </execution>
    </system-under-test>
    <assert>
      <equalTo>
        <query connectionString="Provider=MSOLAP.4;Data Source=(local)\SQL2017;Initial Catalog='Adventure Works DW 2012';localeidentifier=1049">
          select
          [Measures].[Internet Order Count] on 0,
          [Date].[Date].Children  on 1
          from
          [Adventure Works]
        </query>
      </equalTo>
    </assert>
  </test>
```

**Comment by Seddryck** [comment]
It makes sense in the following case "The two queries are connected to two different databases". 

About hash comparison, what's your problem? Anyway, no you shouldn't have any collision, the system-under-test and the assertion are not conflicting.

About samples, well sometimes, Sometimes, I completely forget to update the name of the test so it's possible that they don't match. Some tests are really dummy because these samples are primarily written to run acceptance tests (and in that case comparing two queries running on the same dataset will always expected a success). Anyway, thx for you feedback, I will try to improve this area.

Will be easier to help you if you tell me what you're looking for :-)

**Comment by win32nipuh** [comment]
Thank you.
It is clear: It makes sense in the following case "The two queries are connected to two different databases".

But what if there are the same server, db, tables? (see my post above about your sample)

**Comment by Seddryck** [comment]
It make little sense (I see a case but it would be a poor implementation of a weird case). 

As explained in my previous answer from time to time the samples make no sense because they are primarily targeting acceptance tests of the framework itself. If you're running through them you should find more interesting tests.

**Comment by win32nipuh** [comment]
> Will be easier to help you if you tell me what you're looking for :-)

Ok, I have created the small TestSuite and  received the problem like 
The expected data set has some duplicated keys. Check your keys definition or the result set defined in your .... The duplicated hashcode is ....
Row to insert:....
Row already inserted..."

My queries return 20000 rows set with 2 integer fields.
For the testing I use the same data source in both queries.

I am trying to understand how it is possible. My 2nd question (see in issues) connected to this: I'd like to change the framework (to output dictionary when this exception occurs etc) to catch why it happens.

**Comment by Seddryck** [comment]
> Ok, I have created the small TestSuite and  received the problem like
> The expected data set has some duplicated keys. Check your keys definition or the result set defined in your .... The duplicated hashcode is ....

The "expected dataset" is the set that you've defined in your assertion. This dataset has some rows having the same value for the key column. This is not allowed when using an assertion ```equal-to```. The (first) two rows  sharing the same key are reported in the details with ```Row to insert:....```
 and ```Row already inserted...```.

The problem could be in the development of your solution or a poor definition of the key in the test. If it's the last case then you should read the [documentation about keys](www.nbi.io/docs/compare-configuration/)

**Comment by win32nipuh** [comment]
Ok, thank you , I will check the details. 
Btw, what is interesting: when I repeat the test I receive this error for different keys. It seems it occurs randomly but why....
And yet one thing: in these cases 
` <parallelize-queries>true</parallelize-queries>
`

**Comment by win32nipuh** [comment]
By the way: this table has another column with unique values.
I have added this column to the query and did not receive the error about duplication.

**Comment by Seddryck** [comment]
C'mon read the links that I provided

**Comment by Seddryck** [comment]
>Ok, thank you , I will check the details.
Btw, what is interesting: when I repeat the test I receive this error for different keys. It seems it occurs randomly but why....
And yet one thing: in these cases
<parallelize-queries>true</parallelize-queries>

That's because SQL doesn't guarantee the ordering of the rows! That's probably why I wrote "(first)" ... Please, read my answers and stop to think that you've found a bug. Read the documentation and if you've a question, explain what you're trying to do and not how you're trying to achieve something without having read the documentation.

**Comment by win32nipuh** [comment]
ok, ok, I do not think that I have found a bug, sorry. I am trying to understand what happens in my case. 
I use 'order by' in the query.

**Comment by win32nipuh** [comment]
By the way: after reading the new question in Issues I have checked again my case: 

If I set parallelize-queries=false then it works, I repeat the test many times - no errors, else the test gives me 'Duplicate keys' error on different records on the same queries.

**Comment by Seddryck** [comment]
Please provide steps to reproduce your case and paste full error messages. I’ve really no idea about what you are talking about.
