### ISSUE TITLE
Support: How to change Tests display in NUnit

### ISSUE THREAD

**Issue by Postarion** [Seddryck/NBi#525]
Hello,
I would like to display my tests in NUnit divided to segments, for example:
1. Poland:
    - Sale (couple of tests)
    - Stock (couple of tests)
2. Czech:
   - Sale
   - Stock

Is it possible with NBI?

Right know my tests show only 1 column, for example:
- poland sale
- poland stock
- czech sale
- czech stock
...

**Comment by Seddryck** [comment]
No it's not possible to support a hierarchical view of the tests in NUnit v2.x (due to the hacking performed by NBi to read the tests). This is something on the to-do list when we'll move to NUnit 3.x ... hopefully before EOY 2019.

Nevertheless, you can make the best use of a hierarchical view when writing your tests with the help of the `<group>` elements http://www.nbi.io/docs/metadata-group/
